export const GET_APP_CONFIG = "GET_APP_CONFIG";

export const GET_NAVIGATION = "GET_NAVIGATION";

export const GET_HOME_SCREEN_DATA = "GET_HOME_SCREEN_DATA";

export const LOAD_PRODUCTS_BY_TAG = "LOAD_PRODUCTS_BY_TAG";

export const LOAD_GET_CUSTOMERLIST = "LOAD_GET_CUSTOMERLIST";

export const LOAD_GET_CUSTOMERGROUPSLIST = "LOAD_GET_CUSTOMERGROUPSLIST";

export const LOAD_GET_CUSTOMER_IN_GROUPSLIST = "LOAD_GET_CUSTOMER_IN_GROUPSLIST";

export const LOAD_GET_PRODUCTS_BY_CATEGORY = "LOAD_GET_PRODUCTS_BY_CATEGORY";

export const LOAD_ORDERS_BY_ID = "LOAD_ORDERS_BY_ID";

export const CLEAR_DATA = "CLEAR_DATA";

export const CLEAR_STATUS_CODE = "CLEAR_STATUS_CODE";

export const LOAD_GET_CUSTOMERS_LIST = "LOAD_GET_CUSTOMERS_LIST";

export const COUPONS_LIST = "COUPONS_LIST";

export const ORDERS_COUNT = "ORDERS_COUNT";

export const OPTIONS_LIST = "ORDERS_COUNT";

export const MERCHANT_INFO = "MERCHANT_INFO";

export const SET_LOADING = 'SET_LOADING';

export const CLEAR_LOADING = 'CLEAR_LOADING';

